using System;
using System.ComponentModel;
using UnityEngine;
#if UNITY_AI_ASSET_LABEL_FIX
using UnityEditor;
using UnityEditor.Search;
using System.Collections.Generic;
using System.Linq;
#endif

namespace Unity.AI.Toolkit.Compliance
{
    /// <summary>
    /// Legal related constants.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static class Legal
    {
        /// <summary>
        /// The label used to mark assets generated by Unity AI.
        /// </summary>
        public const string UnityAIGeneratedLabel = "Unityai";

#if UNITY_AI_ASSET_LABEL_FIX
        [InitializeOnLoadMethod]
        static void FixDeprecatedLabelsOnLoad()
        {
            if (Application.isBatchMode)
                return;

            EditorApplication.delayCall += FixDeprecatedLabels;
        }

        static void FixDeprecatedLabels()
        {
            var searchQuery = $"l:\"{k_UnityAIGeneratedLabelDeprecated}\"";

            var context = new SearchContext(SearchService.GetActiveProviders().Where(p => p.id == "asset").ToList(), searchQuery);
            SearchService.Request(context, (_, items) => {
                var foundAssetPaths = new List<string>();
                foreach (var item in items)
                {
                    var assetPath = SearchUtils.GetAssetPath(item);
                    if (string.IsNullOrEmpty(assetPath))
                        continue;
                    if (!AssetDatabase.GetLabels(AssetDatabase.GUIDFromAssetPath(assetPath)).Contains(k_UnityAIGeneratedLabelDeprecated))
                        continue;
                    foundAssetPaths.Add(assetPath);
                }
                if (foundAssetPaths.Count == 0)
                    return;

                Debug.Log($"Found {foundAssetPaths.Count} asset(s) with '{k_UnityAIGeneratedLabelDeprecated}' -> '{UnityAIGeneratedLabel}' label via SearchService. Processing...");

                var fixedCount = 0;
                var changesMade = false;
                foreach (var assetPath in foundAssetPaths)
                {
                    var asset = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(assetPath);
                    if (asset == null)
                    {
                        Debug.LogWarning($"Could not load asset at path: {assetPath})");
                        continue;
                    }

                    var labels = AssetDatabase.GetLabels(asset).ToList();
                    if (labels.Remove(k_UnityAIGeneratedLabelDeprecated))
                    {
                        if (!labels.Contains(UnityAIGeneratedLabel))
                            labels.Add(UnityAIGeneratedLabel);

                        AssetDatabase.SetLabels(asset, labels.ToArray());
                        fixedCount++;
                        changesMade = true;
                    }
                }

                if (changesMade)
                {
                    AssetDatabase.SaveAssets();
                    Debug.Log($"Label fix complete. Fixed '{k_UnityAIGeneratedLabelDeprecated}' label to '{UnityAIGeneratedLabel}' on {fixedCount} asset(s). Asset database saved.");
                }
                else
                {
                    Debug.Log($"Processed {foundAssetPaths.Count} asset(s) found with '{k_UnityAIGeneratedLabelDeprecated}', but no actual label changes were required during processing.");
                }
            }, SearchFlags.Default);
        }

        const string k_UnityAIGeneratedLabelDeprecated = "Unity AI";
#endif
    }
}
